FROM ubuntu:latest as builder
FROM scratch AS final
# 从构建器阶段复制时区数据
COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
# 设置时区环境变量
ENV TZ=Asia/Shanghai
COPY target/x86_64-unknown-linux-musl/release/rust_http_proxy /
ENTRYPOINT ["/rust_http_proxy"]