FROM debian:bookworm
COPY target/release/rust_http_proxy rust_http_proxy
RUN apt-get update \
    && apt-get upgrade -y ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
ENTRYPOINT ["./rust_http_proxy"]
CMD [ "-p=8888","--enable-github-proxy","--append-upstream-url=https://cdnjs.cloudflare.com"]
