FROM docker.io/redhat/ubi10:latest
RUN dnf install -y ca-certificates iproute zlib elfutils-libelf tzdata
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" > /etc/timezone;
COPY target/release/rust_http_proxy rust_http_proxy
ENTRYPOINT ["./rust_http_proxy"]
CMD [ "-p=8888","--enable-github-proxy","--append-upstream-url=https://cdnjs.cloudflare.com"]
