# 反向代理配置文件示例 (TOML格式)

# default_host 配置
[[default_host]]
location = "/v1/chat/completions"
upstream = { url_base = "https://models.inference.ai.azure.com/chat/completions" }

[[default_host]]
location = "/grafana"
upstream = { url_base = "http://192.168.5.16:3000/grafana", headers = [
    ["Host", "${host}"],
] }

# localhost 配置  
[["127.0.0.1"]]
location = "/"
upstream = { url_base = "https://www.baidu.com", version = "H1" }
