name: auto_release

on:
  push:
    branches: [ "**"]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  USE_MUSL: true

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short=8 HEAD)" >> $GITHUB_OUTPUT
      # - name: build gnu
      #   run: |
      #     cargo build --release
      - name: build musl
        id: build_musl
        uses: arloor/rust_musl_action@latest
        with:
          musl_version: 1.2.5
          use_musl: ${{ env.USE_MUSL }}
          extra_deps: cmake
          args: --no-default-features --features aws_lc_rs,jemalloc
      - name: docker build and push
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' 
        run: |
          ls -lh ${{ steps.build_musl.outputs.release_dir }}
          dockerfile="Dockerfile.gnu"
          if [ "${{ env.USE_MUSL }}" = "true" ]; then
            dockerfile="Dockerfile.musl"
          fi
          podman build -f ${dockerfile} . -t docker.io/arloor/rust_http_proxy:${{ steps.vars.outputs.sha_short }} -t docker.io/arloor/rust_http_proxy:latest
          podman login docker.io -u arloor -p ${{ secrets.REGISTRY_PASSWORD }}
          podman push docker.io/arloor/rust_http_proxy:${{ steps.vars.outputs.sha_short }}
          podman push docker.io/arloor/rust_http_proxy:latest
      - name: gihub release
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' 
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # 从Cargo.toml中提取版本号
          version=$(grep -E ^version Cargo.toml|awk -F "[\"]" '{print $2}')
          if [ -z "$version" ]; then echo "version not found"; exit 1; fi
          if $(gh release delete v${version} -y --cleanup-tag); 
            then echo "delete old release"; 
            else echo "no old release";
          fi
          git config --local user.email "admin@arloor.com"
          git config --local user.name "arloor"
          gh release create v${version} ${{ steps.build_musl.outputs.release_dir }}rust_http_proxy -n "$version" --latest -t "$version"
          
#    - name: install ssh keys
#      run: |
#        install -m 600 -D /dev/null ~/.ssh/id_rsa
#        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
#        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
#    - name: connect and pull
#      run: ssh root@${{ secrets.SSH_HOST }} "kubectl set image ds proxy proxy=docker.io/arloor/rust_http_proxy:${{ github.sha }}"
#    - name: cleanup
#      run: rm -rf ~/.ssh