name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  REGISTRY_USER: arloor
  IMAGE_REGISTRY: docker.io
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build-and-push
      run: |
        cargo build --release
        podman build  -f Dockerfile . -t docker.io/arloor/rust_http_proxy:${{ github.sha }} -t docker.io/arloor/rust_http_proxy:latest
        podman login docker.io -u arloor -p ${{ env.REGISTRY_PASSWORD }}
        podman push docker.io/arloor/rust_http_proxy:${{ github.sha }}
        podman push docker.io/arloor/rust_http_proxy:latest