name: Update

on:
  push:
    branches: [ "master","feature/low-level","feature/low-level-timed","tmp_hyper1" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  REGISTRY_USER: arloor
  IMAGE_REGISTRY: docker.io
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short=8 HEAD)" >> $GITHUB_OUTPUT
      - name: build
        run: |
          cargo build --release
      - name: gihub_release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cp target/release/rust_http_proxy target/release/rust_http_proxy_linux; 
          if $(gh release delete v1.0.0 -y --cleanup-tag); 
            then echo "delete old release"; 
            else echo "no old release";
          fi
          git config --local user.email "admin@arloor.com"
          git config --local user.name "arloor"
          git tag  v1.0.0 -m 'latest'
          git push origin v1.0.0
          gh release create v1.0.0 target/release/rust_http_proxy_linux --notes-from-tag --latest -t latest 
      - name: push
        run: |
          podman build  -f Dockerfile . -t docker.io/arloor/rust_http_proxy:${{ steps.vars.outputs.sha_short }} -t docker.io/arloor/rust_http_proxy:latest
          podman login docker.io -u arloor -p ${{ env.REGISTRY_PASSWORD }}
          podman push docker.io/arloor/rust_http_proxy:${{ steps.vars.outputs.sha_short }}
          podman push docker.io/arloor/rust_http_proxy:latest
          
#    - name: install ssh keys
#      run: |
#        install -m 600 -D /dev/null ~/.ssh/id_rsa
#        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
#        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
#    - name: connect and pull
#      run: ssh root@${{ secrets.SSH_HOST }} "kubectl set image ds proxy proxy=docker.io/arloor/rust_http_proxy:${{ github.sha }}"
#    - name: cleanup
#      run: rm -rf ~/.ssh